=== crisbenjamin/1st-sem-MCA/xml/reviews.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Reads">
<xs:complexType>
<xs:sequence>
<xs:element name="Reviews" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name ="title" type="xs:string"/>
<xs:element name ="author" type="xs:string"/>
<xs:element name ="reviewer" type="xs:string"/>
<xs:element name ="rating" type="xs:float"/>
<xs:element name="review" type="criteria"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="criteria">
<xs:restriction base="xs:string">
<xs:minLength value="5"></xs:minLength>
<xs:maxLength value="500"></xs:maxLength>
</xs:restriction>
</xs:simpleType> 
</xs:schema>

=== crisbenjamin/1st-sem-MCA/xml/reviews.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="reviews.xsl"?>
<Reads xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reviews.xsd">
  <Reviews>
    <title>Mad at the World</title>
    <author>William Souder</author>
    <reviewer>Jane Doe</reviewer>
    <rating>4.2</rating>
    <review>John Steinbeck just might be the novelist for our time. In his sprawling epic The Grapes of Wrath, he captured Americans’ peculiar yearning for a life not their own, the promise of wealth beyond the veil of desolation and the wretched impossibility of such a promise.</review>
  </Reviews>
  <Reviews>
    <title>A Time for Mercy</title>
    <author>John Grisham</author>
    <reviewer>John Doe</reviewer>
    <rating>4</rating>
    <review>With nationwide calls for police reform and defunding, literary giant John Grisham’s novel A Time for Mercy is undoubtedly timely, as it explores the ways that violence committed by or against law enforcement officials can complicate the pursuit of justice.</review>
  </Reviews>
  <Reviews>
    <title>Black Sun</title>
    <author>Rebecca Roanhorse</author>
    <reviewer>Bob Smith</reviewer>
    <rating>3.9</rating>
    <review>Readers will be riveted by powerful world building and deep characterization for the entirety of Rebecca Roanhorse’s Black Sun</review>
  </Reviews>
</Reads>
